name: Antarctic Journal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27405f'
    - '#874434'
    - '#7f859b'
    - '#fefcfe'
    - '#c7c6d4'
  brandStrength: 1
  lightness: 0.9195937584154308
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
