name: Antarctic Journal
favicon: null
layout_spectrum: 0.1392814910504967
typography_spectrum: 0.05299407965503633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.39407462859526277
  lightness: 0.9195937584154308
  saturation: 0.7081612416077405
  rhythmicContrast: 0.47139558801427484
purpose: []
